- name: ATOM
  subtype: service
  filters:
    ors:
      - type: simple
        object: content
        value: 'http://www.w3.org/2005/Atom'
  service_description:
  datasets:
  metadatas:
  errors:
  versions: